/*************************************************************************\
* 望友引擎1.0
* Copyright (c) 2018-2018 authored by 朱加浩
* 提供给用户使用的头文件
\*************************************************************************/
#ifndef __VAYO_H__
#define __VAYO_H__

// 引擎入口
#include "VayoRoot.h"
// 框架基础
#include "VayoCommon.h"
#include "VayoSupport.h"
// 输入事件
#include "VayoInput.h"
// 图形用户界面
#include "VayoBaseGUI.h"
#include "VayoCoreGUI.h"
// 插件模块
#include "VayoPlugin.h"
#include "VayoDynLib.h"
#include "VayoDynLibManager.h"
// 客户端网络模块
#include "VayoSocket.h"
// 其他主要模块
#include "VayoDevice.h"
#include "VayoRenderSystem.h"
#include "VayoScriptSystem.h"
#include "VayoLanguage.h"
#include "VayoDatabaseCSV.h"
#include "VayoConfigManager.h"
// 工具类/函数
#include "VayoAny.h"
#include "VayoLog.h"
#include "VayoUtils.h"
#include "VayoTimer.h"
#include "VayoTable.h"
#include "VayoFileIO.h"
#include "VayoSigslot.h"
#include "VayoArcball.h"
#include "VayoBitState.h"
#include "VayoSharedPtr.h"
#include "VayoSingleton.h"
#include "VayoReflection.h"
#include "VayoUserDataBind.h"
#include "VayoTessGridBuilder.h"
#include "VayoTessGridHandler.h"
#include "VayoAttribSerializer.h"
// 数学库
#include "VayoMath.h"
#include "VayoVector2d.h"
#include "VayoLine2d.h"
#include "VayoDimension2d.h"
#include "VayoRectangle.h"
#include "VayoVector3d.h"
#include "VayoLine3d.h"
#include "VayoPlane3d.h"
#include "VayoAabbox3d.h"
#include "VayoTriangle3d.h"
#include "VayoMatrix4x4.h"
#include "VayoQuaternion.h"
// 场景元素
#include "VayoMovableObject.h"
#include "VayoLight.h"
#include "VayoFrustum.h"
#include "VayoCamera.h"
#include "VayoEntity.h"
#include "VayoRenderable.h"
#include "VayoTiledMap.h"
#include "VayoManualObject.h"
#include "VayoTextObject.h"
#include "VayoNode.h"
#include "VayoNodeAnimator.h"
#include "VayoCollision.h"
#include "VayoSceneNode.h"
#include "VayoSceneManager.h"
#include "VayoVertex.h"
#include "VayoMesh.h"
#include "VayoMeshManager.h"
#include "VayoColour.h"
#include "VayoLightData.h"
#include "VayoSpriteBox.h"
#include "VayoImage.h"
#include "VayoTexture.h"
#include "VayoTextureLayer.h"
#include "VayoTextureManager.h"
#include "VayoTesselator.h"
#include "VayoDisplayList.h"
#include "VayoMaterial.h"
#include "VayoMaterialRenderer.h"
#include "VayoMaterialManager.h"
// 应用程序基类
#include "VayoApp.h"

#endif // __VAYO_H__
